export const API_ROUTES = {
  health: "/api/v1/health",
  auth: {
    register: "/api/v1/auth/register",
    login: "/api/v1/auth/login",
    google: "/api/v1/auth/google",
    verifyEmail: "/api/v1/auth/verify-email",
    resendVerification: "/api/v1/auth/resend-verification",
    me: "/api/v1/auth/me",
    logout: "/api/v1/auth/logout",
    forgotPassword: "/api/v1/auth/forgot-password",
    resetPassword: "/api/v1/auth/reset-password",
    refresh: "/api/v1/auth/refresh",
    invite: (token: string) => `/api/v1/auth/invite/${token}`,
    acceptInvite: "/api/v1/auth/accept-invite",
  },
  products: {
    list: "/api/v1/products",
    search: "/api/v1/products/search",
    collections: "/api/v1/products/collections",
    slugs: "/api/v1/products/slugs",
    detail: (slug: string) => `/api/v1/products/${slug}`,
    related: (slug: string) => `/api/v1/products/${slug}/related`,
  },
  reviews: {
    product: (slug: string) => `/api/v1/reviews/product/${slug}`,
    invite: (token: string) => `/api/v1/reviews/invite/${token}`,
    submit: "/api/v1/reviews",
  },
  categories: {
    list: "/api/v1/categories",
  },
  cart: {
    root: "/api/v1/cart",
    items: "/api/v1/cart/items",
    item: (itemId: string) => `/api/v1/cart/items/${itemId}`,
  },
  orders: {
    list: "/api/v1/orders",
    checkout: "/api/v1/orders/checkout",
    verifyPayment: "/api/v1/orders/verify-payment",
    paymentFailed: "/api/v1/orders/payment-failed",
    track: "/api/v1/orders/track",
    detail: (orderNumber: string) => `/api/v1/orders/${orderNumber}`,
  },
  wishlist: {
    root: "/api/v1/wishlist",
    item: (slug: string) => `/api/v1/wishlist/${slug}`,
  },
  appointments: "/api/v1/appointments",
  contact: "/api/v1/contact",
  customFurniture: {
    catalog: "/api/v1/custom-furniture/catalog",
    estimate: "/api/v1/custom-furniture/estimate",
    chat: "/api/v1/assistant/chat",
    quote: "/api/v1/custom-furniture/quote",
  },
  newsletter: {
    subscribe: "/api/v1/newsletter/subscribe",
    unsubscribe: "/api/v1/newsletter/unsubscribe",
  },
  blog: {
    list: "/api/v1/blog",
    detail: (slug: string) => `/api/v1/blog/${encodeURIComponent(slug)}`,
  },
  admin: {
    stats: "/api/v1/admin/stats",
    notifications: "/api/v1/admin/notifications",
    notificationsReadAll: "/api/v1/admin/notifications/read-all",
    notificationRead: (id: string) => `/api/v1/admin/notifications/${id}/read`,
    uploadImage: "/api/v1/admin/uploads/image",
    assignees: "/api/v1/admin/assignees",
    orders: "/api/v1/admin/orders",
    order: (orderNumber: string) => `/api/v1/admin/orders/${orderNumber}`,
    appointments: "/api/v1/admin/appointments",
    appointment: (id: string) => `/api/v1/admin/appointments/${id}`,
    contacts: "/api/v1/admin/contacts",
    contact: (id: string) => `/api/v1/admin/contacts/${id}`,
    customQuotes: "/api/v1/admin/custom-quotes",
    customQuote: (id: string) => `/api/v1/admin/custom-quotes/${id}`,
    newsletter: "/api/v1/admin/newsletter",
    newsletterSubscriber: (id: string) => `/api/v1/admin/newsletter/${id}`,
    products: "/api/v1/admin/products",
    product: (slug: string) => `/api/v1/admin/products/${slug}`,
    productStatus: (slug: string) => `/api/v1/admin/products/${slug}/status`,
    categories: "/api/v1/admin/categories",
    category: (id: string) => `/api/v1/admin/categories/${id}`,
    categorySubcategories: (id: string) => `/api/v1/admin/categories/${id}/subcategories`,
    categorySubcategory: (id: string, subId: string) =>
      `/api/v1/admin/categories/${id}/subcategories/${subId}`,
    customers: "/api/v1/admin/customers",
    customer: (id: string) => `/api/v1/admin/customers/${id}`,
    staff: "/api/v1/admin/staff",
    staffInvites: "/api/v1/admin/staff/invites",
    staffInvite: (id: string) => `/api/v1/admin/staff/invites/${id}`,
    deactivateStaff: (id: string) => `/api/v1/admin/staff/${id}/deactivate`,
    content: "/api/v1/admin/content",
    contentItem: (key: string) => `/api/v1/admin/content/${encodeURIComponent(key)}`,
    blog: "/api/v1/admin/blog",
    blogPost: (id: string) => `/api/v1/admin/blog/${id}`,
  },
  content: {
    list: "/api/v1/content",
    detail: (key: string) => `/api/v1/content/${encodeURIComponent(key)}`,
  },
} as const;
